# Generated by Django 3.1 on 2020-09-15 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=67)),
                ('email', models.CharField(max_length=58)),
                ('password', models.CharField(max_length=58)),
                ('repass', models.CharField(max_length=58)),
            ],
        ),
    ]
