# Generated by Django 3.1 on 2020-09-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threeknots', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='repass',
            new_name='password_repeat',
        ),
        migrations.RenameField(
            model_name='login',
            old_name='first_name',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='login',
            name='email',
            field=models.EmailField(max_length=58),
        ),
    ]
