# Generated by Django 3.1 on 2020-10-02 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threeknots', '0002_auto_20200928_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='pets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petname', models.CharField(max_length=30)),
            ],
        ),
    ]
