# Generated by Django 3.1 on 2020-11-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threeknots', '0004_auto_20201118_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='about',
            field=models.CharField(max_length=98, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='venue',
            name='rooms',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='venue',
            name='seats',
            field=models.IntegerField(),
        ),
    ]
