# Generated by Django 3.1 on 2020-11-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threeknots', '0005_auto_20201119_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='about',
            field=models.TextField(max_length=98, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='type',
            field=models.CharField(choices=[('banquet halls', 'BANQUET HALLS'), ('hotels', 'HOTELS'), ('Small functions halls', 'SMALL FUNCTION HALLS'), ('resorts', 'RESORTS')], default='green', max_length=100),
        ),
    ]
