# Generated by Django 3.1 on 2020-11-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threeknots', '0006_auto_20201119_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='aminiti',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
