# Generated by Django 3.1 on 2020-11-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threeknots', '0007_venue_aminiti'),
    ]

    operations = [
        migrations.CreateModel(
            name='pets_sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petname', models.CharField(max_length=100)),
                ('breedname', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.CharField(max_length=100)),
            ],
        ),
    ]
