# Generated by Django 3.1 on 2020-11-20 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threeknots', '0008_pets_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pets_sale',
            name='breedname',
        ),
        migrations.RemoveField(
            model_name='pets_sale',
            name='petname',
        ),
    ]
