# Generated by Django 3.1 on 2020-11-20 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threeknots', '0009_auto_20201120_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='aminiti',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='type',
        ),
    ]
