# Generated by Django 3.1 on 2020-11-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threeknots', '0011_auto_20201120_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='type',
            field=models.CharField(choices=[('banquet halls', 'BANQUET HALLS'), ('hotels', 'HOTELS'), ('Small functions halls', 'SMALL FUNCTION HALLS'), ('resorts', 'RESORTS')], default='green', max_length=100),
        ),
    ]
