# Generated by Django 3.1 on 2020-11-21 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threeknots', '0012_venue_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ven',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banquet_halls', models.CharField(max_length=60)),
                ('hotels', models.CharField(max_length=60)),
                ('function_halls', models.CharField(max_length=60)),
                ('resorts', models.CharField(max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='pets_sale',
        ),
    ]
