# Generated by Django 3.1 on 2020-11-21 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threeknots', '0013_auto_20201121_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
