# Generated by Django 3.1 on 2020-11-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threeknots', '0014_auto_20201121_0841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ven',
            name='banquet_halls',
        ),
        migrations.RemoveField(
            model_name='ven',
            name='function_halls',
        ),
        migrations.RemoveField(
            model_name='ven',
            name='hotels',
        ),
        migrations.RemoveField(
            model_name='ven',
            name='resorts',
        ),
        migrations.AddField(
            model_name='ven',
            name='type',
            field=models.CharField(choices=[('banquet_halls', 'BANQUET_HALLS'), ('hotels', 'HOTELS'), (' function_halls', 'FUNCTION_HALLS'), ('  resorts', 'RESORTS')], max_length=100, null=True, unique=True),
        ),
    ]
