# Generated by Django 3.1 on 2020-11-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threeknots', '0015_auto_20201123_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='ameniti',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='about',
            field=models.TextField(max_length=98),
        ),
    ]
