# Generated by Django 3.1 on 2020-11-24 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threeknots', '0016_auto_20201124_1301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='ameniti',
            new_name='checks',
        ),
    ]
