# Generated by Django 3.1 on 2020-11-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threeknots', '0017_auto_20201124_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='invi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=58)),
                ('address', models.CharField(max_length=58)),
                ('number', models.IntegerField()),
                ('ctype', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.IntegerField()),
                ('list', models.IntegerField()),
                ('about', models.TextField(max_length=98)),
                ('image1', models.ImageField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Ven',
        ),
    ]
