# Generated by Django 3.1 on 2020-11-25 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threeknots', '0020_pandii'),
    ]

    operations = [
        migrations.CreateModel(
            name='cater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=58)),
                ('address', models.CharField(max_length=58)),
                ('number', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('style', models.CharField(max_length=100)),
                ('package', models.CharField(max_length=100)),
                ('others', models.CharField(max_length=58)),
                ('about', models.TextField(max_length=98, null=True)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='decor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=58)),
                ('address', models.CharField(max_length=58)),
                ('number', models.IntegerField()),
                ('special', models.CharField(max_length=100)),
                ('about', models.TextField(max_length=98, null=True)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='make',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=58)),
                ('address', models.CharField(max_length=58)),
                ('number', models.IntegerField()),
                ('makeup', models.CharField(max_length=100)),
                ('offer', models.CharField(max_length=100)),
                ('about', models.TextField(max_length=98, null=True)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=58)),
                ('address', models.CharField(max_length=58)),
                ('number', models.IntegerField()),
                ('package', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('ameniti', models.CharField(max_length=100)),
                ('about', models.TextField(max_length=98, null=True)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
