# Generated by Django 3.1 on 2020-11-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threeknots', '0021_cater_decor_make_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invi',
            old_name='price',
            new_name='bprice',
        ),
        migrations.RenameField(
            model_name='invi',
            old_name='image',
            new_name='other',
        ),
        migrations.RemoveField(
            model_name='invi',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='invi',
            name='list',
        ),
        migrations.AddField(
            model_name='invi',
            name='boxed',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='invi',
            name='otherc',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invi',
            name='otheri',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='invi',
            name='othprice',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='invi',
            name='scroll',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='invi',
            name='sprice',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='invi',
            name='uboxed',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='invi',
            name='unprice',
            field=models.IntegerField(null=True),
        ),
    ]
