# Generated by Django 3.1 on 2020-11-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threeknots', '0022_auto_20201125_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='cater',
            name='otherstyle',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
