# Generated by Django 3.1 on 2020-11-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threeknots', '0023_cater_otherstyle'),
    ]

    operations = [
        migrations.CreateModel(
            name='band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=58)),
                ('style', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=58)),
                ('number', models.IntegerField()),
                ('event', models.CharField(max_length=100)),
                ('others', models.CharField(max_length=100, null=True)),
                ('about', models.TextField(max_length=98)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='djchoreo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=58)),
                ('vendor', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=58)),
                ('number', models.IntegerField()),
                ('genres', models.CharField(max_length=100)),
                ('othergen', models.CharField(max_length=58)),
                ('choreo', models.CharField(max_length=100, null=True)),
                ('otherchoreo', models.CharField(max_length=58)),
                ('about', models.TextField(max_length=98)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
