# Generated by Django 3.1 on 2020-11-26 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threeknots', '0024_band_djchoreo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='venue',
            new_name='venuep',
        ),
    ]
