# Generated by Django 3.1 on 2020-12-01 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('threeknots', '0026_user_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='threeknots.band')),
                ('cater', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='threeknots.cater')),
                ('decor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='threeknots.decor')),
                ('djchoreo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='threeknots.djchoreo')),
                ('invi', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='threeknots.invi')),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='threeknots.make')),
                ('pandii', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='threeknots.pandii')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='threeknots.photo')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='threeknots.user')),
                ('venuep', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='threeknots.venuep')),
            ],
        ),
    ]
