# Generated by Django 3.1 on 2020-12-02 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('threeknots', '0028_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='vendorty',
        ),
        migrations.AddField(
            model_name='cart',
            name='venuep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='threeknots.venuep'),
        ),
    ]
