# Generated by Django 3.1 on 2020-12-03 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threeknots', '0029_auto_20201202_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='vendortable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=58)),
                ('address', models.CharField(max_length=58)),
                ('vendortype', models.CharField(max_length=58)),
                ('customerid', models.CharField(max_length=58)),
                ('type', models.CharField(max_length=100, null=True)),
                ('hallsize', models.CharField(max_length=58, null=True)),
                ('seats', models.IntegerField()),
                ('rooms', models.IntegerField()),
                ('number', models.IntegerField()),
                ('checks', models.CharField(max_length=100, null=True)),
                ('about', models.TextField(max_length=98)),
                ('image', models.ImageField(upload_to='')),
                ('ctype', models.CharField(max_length=100, null=True)),
                ('boxed', models.ImageField(null=True, upload_to='')),
                ('uboxed', models.ImageField(null=True, upload_to='')),
                ('scroll', models.ImageField(null=True, upload_to='')),
                ('bprice', models.IntegerField()),
                ('unprice', models.IntegerField(null=True)),
                ('sprice', models.IntegerField(null=True)),
                ('othprice', models.CharField(max_length=80, null=True)),
                ('otherc', models.CharField(max_length=100, null=True)),
                ('otheri', models.ImageField(null=True, upload_to='')),
                ('other', models.ImageField(null=True, upload_to='')),
                ('experi', models.CharField(max_length=100, null=True)),
                ('service', models.CharField(max_length=100, null=True)),
                ('lang', models.CharField(max_length=100, null=True)),
                ('special', models.CharField(max_length=100, null=True)),
                ('catertype', models.CharField(max_length=100, null=True)),
                ('style', models.CharField(max_length=100, null=True)),
                ('otherstyle', models.CharField(max_length=100, null=True)),
                ('package', models.CharField(max_length=100, null=True)),
                ('others', models.CharField(max_length=58, null=True)),
                ('photopackage', models.CharField(max_length=100, null=True)),
                ('price', models.CharField(max_length=100, null=True)),
                ('ameniti', models.CharField(max_length=100, null=True)),
                ('makeup', models.CharField(max_length=100, null=True)),
                ('offer', models.CharField(max_length=100, null=True)),
                ('bandstyle', models.CharField(max_length=100, null=True)),
                ('event', models.CharField(max_length=100)),
                ('bandothers', models.CharField(max_length=100, null=True)),
                ('vendor', models.CharField(max_length=100, null=True)),
                ('genres', models.CharField(max_length=100, null=True)),
                ('othergen', models.CharField(max_length=58, null=True)),
                ('choreo', models.CharField(max_length=100, null=True)),
                ('otherchoreo', models.CharField(max_length=58, null=True)),
            ],
        ),
    ]
