# Generated by Django 3.1 on 2020-12-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threeknots', '0030_vendortable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendortable',
            name='bprice',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vendortable',
            name='event',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
