# Generated by Django 3.1 on 2020-12-03 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threeknots', '0031_auto_20201203_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='quotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendorid', models.CharField(max_length=100)),
                ('fdate', models.DateField(max_length=100)),
                ('ldate', models.DateField(max_length=100)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('mob', models.CharField(max_length=100)),
                ('ame', models.CharField(max_length=100)),
                ('guest', models.CharField(max_length=100)),
                ('rooms', models.CharField(max_length=100)),
            ],
        ),
    ]
