# Generated by Django 3.1 on 2020-12-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threeknots', '0033_quotation_customeri'),
    ]

    operations = [
        migrations.CreateModel(
            name='res',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cusid', models.CharField(max_length=100)),
                ('amt', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='vendortable',
            name='rooms',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vendortable',
            name='seats',
            field=models.IntegerField(null=True),
        ),
    ]
