# Generated by Django 3.1 on 2020-12-04 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('threeknots', '0034_auto_20201203_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='res',
            name='vendori',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='threeknots.vendortable'),
            preserve_default=False,
        ),
    ]
