# Generated by Django 3.1 on 2020-12-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threeknots', '0035_res_vendori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='res',
            name='vendori',
            field=models.CharField(max_length=100),
        ),
    ]
