# Generated by Django 3.1 on 2020-12-04 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('threeknots', '0036_auto_20201204_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='res',
            name='vendori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='threeknots.vendortable'),
        ),
    ]
