# Generated by Django 3.1 on 2020-12-05 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threeknots', '0037_auto_20201204_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='res',
            name='vendori',
            field=models.CharField(max_length=100),
        ),
    ]
