# Generated by Django 3.1 on 2020-12-06 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threeknots', '0038_auto_20201205_0737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='venuep',
        ),
    ]
