# Generated by Django 3.1 on 2020-12-06 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('threeknots', '0039_remove_cart_venuep'),
    ]

    operations = [
        migrations.CreateModel(
            name='carty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('added_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_on', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threeknots.user')),
                ('vendortable', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='threeknots.vendortable')),
            ],
        ),
    ]
