# Generated by Django 3.1 on 2020-12-06 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threeknots', '0041_auto_20201206_0913'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart',
        ),
    ]
