# Generated by Django 3.1 on 2020-12-07 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('threeknots', '0043_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='carty',
            name='amount',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='tamount',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carty',
            name='vendort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threeknots.vendortable'),
        ),
    ]
