# Generated by Django 3.1 on 2020-12-12 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threeknots', '0044_auto_20201207_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='airfunct',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='at',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='budget',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='card',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='ctype',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='etype',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='ftype',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='gender',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='itype',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='refunct',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='service',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='style',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='who',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='ame',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='guest',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='rooms',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
