# Generated by Django 3.1 on 2020-12-12 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threeknots', '0045_auto_20201212_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='vendortyp',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
