# Generated by Django 3.1 on 2020-12-12 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threeknots', '0046_quotation_vendortyp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tamount',
        ),
    ]
