# Generated by Django 3.1 on 2020-12-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threeknots', '0047_remove_order_tamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tamount',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
