# Generated by Django 3.1 on 2020-12-15 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threeknots', '0048_order_tamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='carty',
            name='tamount',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
