# Generated by Django 3.1 on 2020-12-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threeknots', '0050_quotation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendortable',
            name='status',
            field=models.CharField(max_length=58, null=True),
        ),
    ]
