# Generated by Django 3.1 on 2020-12-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threeknots', '0051_vendortable_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='cust_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='added_on',
            new_name='processed_on',
        ),
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tamount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='update_on',
        ),
        migrations.RemoveField(
            model_name='order',
            name='vendort',
        ),
        migrations.AddField(
            model_name='order',
            name='cart_ids',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_id',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='vendor_id',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
