# Generated by Django 3.1 on 2020-12-17 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('threeknots', '0052_auto_20201217_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cust_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='tamount',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='carty',
            name='vendort',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='threeknots.vendortable'),
        ),
    ]
