# Generated by Django 3.1 on 2020-12-17 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('threeknots', '0053_auto_20201217_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_ids', models.CharField(max_length=250, null=True)),
                ('vendor_id', models.CharField(max_length=250, null=True)),
                ('tamount', models.CharField(max_length=250, null=True)),
                ('invoice_id', models.CharField(max_length=250, null=True)),
                ('status', models.BooleanField(default=False, null=True)),
                ('processed_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
